# Default ucp config

[theme]
main = dark
round_r = 12

[colours]

bg = 101010ff
fg = 202020ff
txt  = 202020ff

msg_bg = ddddddff
msg_fg = ddddddff
msg_txt = dddddaff

[hotkey]

close = ctrl+p
exit = ctrl+q
change = tab
